### model
model_name_or_path: Qwen/Qwen2.5-VL-7B-Instruct
image_max_pixels: 262144
video_max_pixels: 16384
trust_remote_code: true
video_fps: 8.0

### method
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: false  # choices: [true, false]
freeze_multi_modal_projector: true  # choices: [true, false]
train_mm_proj_only: false  # choices: [true, false]
deepspeed: examples/deepspeed/ds_z3_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: cam_motion_balanced_vqa, cam_motion_imbalanced_vqa, cam_motion_caption
template: qwen2_vl
cutoff_len: 4096
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 64

### output
output_dir: ../saves/qwen2.5_vl-7b/full/sft/bal_imb_cap_full_lr4e-5_epoch5.0_freezevisFalse_fps8
logging_steps: 10
save_steps: 800
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 6
gradient_accumulation_steps: 2
learning_rate: 4.0e-5
num_train_epochs: 10.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
# pure_bf16: true
ddp_timeout: 180000000
flash_attn: fa2
bf16: true
use_adam_mini: false

# eval (taking away samples from training may leave some splits underrepresented)
# val_size: 200
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 1000
