### model
model_name_or_path: chancharikm/qwen2.5-vl-7b-cam-motion-preview
image_max_pixels: 262144
video_max_pixels: 16384
trust_remote_code: true
video_fps: 8.0

### method
stage: dpo
do_train: true
finetuning_type: lora
lora_rank: 16
lora_target: all
pref_beta: 0.1
pref_loss: sigmoid  # choices: [sigmoid (dpo), orpo, simpo]

### dataset
dataset: cambench_sft_dpo_5000
template: qwen2_vl
cutoff_len: 4096
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 64

### output
output_dir: ../saves/qwen2_vl-7b/lora/cambench_sft_dpo_5000
logging_steps: 50
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 5.0e-6
num_train_epochs: 10.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
flash_attn: fa2

### eval
val_size: 25
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
