### model
model_name_or_path: Qwen/Qwen2.5-VL-3B-Instruct
image_max_pixels: 262144
video_max_pixels: 16384
trust_remote_code: true
video_fps: 8.0

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 16
lora_target: all
freeze_vision_tower: true # choices: [true, false]
freeze_multi_modal_projector: true  # choices: [true, false]
deepspeed: examples/deepspeed/ds_z3_config.json 

### dataset
dataset: llava_cot_sft
template: qwen2_vl
cutoff_len: 4096
max_samples: 94000
overwrite_cache: true
preprocessing_num_workers: 128

### output
output_dir: ../saves/qwen2.5_vl-3b/lora/sft
logging_steps: 10
save_steps: 200
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 3.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.03
bf16: true
ddp_timeout: 180000000
flash_attn: fa2
use_adam_mini: false

### eval
# eval_dataset: dasd
val_size: 100
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 200