### model
model_name_or_path: ../models/qwen2.5_vl-3b/llava_cot_sft
image_max_pixels: 262144
video_max_pixels: 16384
trust_remote_code: true

### method
stage: dpo
do_train: true
finetuning_type: lora
lora_rank: 16
lora_target: all
pref_beta: 0.1
pref_loss: sigmoid  # choices: [sigmoid (dpo), orpo, simpo]
freeze_vision_tower: true  # choices: [true, false]
freeze_multi_modal_projector: true  # choices: [true, false]
train_mm_proj_only: false  # choices: [true, false]
use_adam_mini: false


### dataset
dataset: llava_cot_dpo_1, llava_cot_dpo_2, llava_cot_dpo_3
template: qwen2_vl
cutoff_len: 4096
max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 64

### output
output_dir: ../saves/qwen2.5_vl-3b/lora/sft_dpo
logging_steps: 10
save_steps: 400
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 5.0e-6
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.05
bf16: true
ddp_timeout: 180000000
flash_attn: fa2

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
