### model
model_name_or_path: deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 16
lora_target: all

### dataset
dataset: dasd_nosys
template: deepseek3
cutoff_len: 4096
max_samples: 10000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/qwen-distill-1.5b/lora/sft
logging_steps: 10
save_steps: 50
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
flash_attn: fa2
use_adam_mini: false

### eval
# eval_dataset: dasd
val_size: 100
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 50
